# Generated by Django 5.0.3 on 2024-04-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_no", models.IntegerField(default=0)),
                ("password", models.CharField(max_length=100)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("city", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("ward", models.CharField(max_length=100)),
                ("street", models.CharField(max_length=100)),
            ],
        ),
    ]
