# Generated by Django 5.0.2 on 2024-04-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="inactive",
                max_length=8,
            ),
        ),
    ]
